spring.application.name=GetInTouch
cloudflare.r2.access-key=ae6fe7db3c414fadcde7c1c4c2898db5
cloudflare.r2.secret-key=f2734df0ea1c28da9c1082f6ceb9f784501ee8989fc1775ac6574f14468cc80e
cloudflare.r2.endpoint=https://85cfce3d7def8bd085e5d98080f4fb95.r2.cloudflarestorage.com
cloudflare.r2.bucket=notes-storage
cloudflare.r2.public-url=https://pub-79682c7dd4884cb5ade78cc1edce2a6f.r2.dev