spring.application.name=GetInTouch
spring.datasource.url=jdbc:postgresql://getintuch-getintuchdb-dtp7cu:5432/PostgreSQL
spring.datasource.username=getintuchdb
spring.datasource.password=PPyAoU1vnktFieDcOCpF