spring.application.name=GetInTouch

#BOOTSTRAP_ADMIN_EMAIL: admin@getintouch.com
#BOOTSTRAP_ADMIN_PASSWORD: Admin@123
##
##spring.jpa.hibernate.ddl-auto=create-drop
#
## Server
#server.port=8080
#
## PostgreSQL Database
#spring.datasource.url=jdbc:postgresql://dpg-d71qsbfpm1nc73f36opg-a.oregon-postgres.render.com:5432/getintouchdb_k6i1
#spring.datasource.username=getintouchdb_k6i1_user
#spring.datasource.password=FgPVYNgMC4UouBIc2U8lfgyminPsyiJ1
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#
## JWT
#jwt.secret=qP3d9F7KcT8Rk6mX3Y1Y+7YxGk9Xc2M1VZpQ8Hn7Z0Q=